### ISSUE TITLE
Todo Alpha

### ISSUE THREAD

**Issue by dioptre** [dioptre/sflabs#1]
- [x] https://invester-shirley-87706.netlify.com/contact
- [ ] https://invester-shirley-87706.netlify.com/about (for investors)
- [ ] https://invester-shirley-87706.netlify.com/about (for startups)
- [ ] https://invester-shirley-87706.netlify.com/
- [ ]  https://invester-shirley-87706.netlify.com/startups
- [ ] https://invester-shirley-87706.netlify.com/investors 
- [ ] https://invester-shirley-87706.netlify.com/growth
- [ ] https://invester-shirley-87706.netlify.com/index (home page)

**Comment by msmonette** [comment]
I wrote something for the startup section - feel free to change it. It's better than garbled latin!

**Comment by dioptre** [comment]
Thanks! :)
